# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.135:3308/mybatis_plus_db?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=true
    username: root
    password: mysqlHolder
    driverClassName: com.mysql.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.genereator: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: com.baomidou.mybatisplus.samples.genereator.entity
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: false
    call-setters-on-nulls: false
  global-config:
    refresh: false
    db-config:
      db-type: mysql
      id-type: auto
      field-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0