spring:
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://192.168.100.135:3308/mybatis_plus_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password : mysqlHolder
    driverClassName : com.mysql.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl